# service.yaml
kind: Service
apiVersion: v1

metadata:
  name: nginx
  namespace: default

spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 8080
      targetPort: 80

