# deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: assets-manager
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: assets-manager

  template:
    metadata:
      labels:
        app: assets-manager
    spec:
      containers:
      - name: nginx
        image: mptbootcamp/assets-manager:latest
        ports:
        - containerPort: 9000

