# service.yaml
kind: Service
apiVersion: v1

metadata:
  name: assets-manager
  namespace: default

spec:
  type: NodePort
  selector:
    app: assets-manager
  ports:
    - name: http
      port: 9000
      targetPort: 9000

